# Generated by Django 4.0.3 on 2022-03-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoldHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.BigIntegerField()),
                ('returns', models.BigIntegerField()),
            ],
        ),
    ]
