# Generated by Django 4.0.3 on 2022-03-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldhistory',
            name='returns',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='goldhistory',
            name='years',
            field=models.CharField(max_length=50),
        ),
    ]
