# Generated by Django 4.0.3 on 2022-03-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_goldhistory_returns_alter_goldhistory_years'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFundData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MutualFundHouseTop10', models.CharField(max_length=100)),
                ('Column2', models.CharField(max_length=100)),
                ('Column3', models.CharField(max_length=100)),
                ('Column4', models.CharField(max_length=100)),
                ('Column5', models.CharField(max_length=100)),
                ('Column6', models.CharField(max_length=100)),
            ],
        ),
    ]
